/**
 * Имена IPC-каналов без Zod — для preload (не тянуть ipcContracts в sandbox).
 * В main/renderer используйте `ipcContracts` (IPC реэкспортируется отсюда).
 */
export const IPC = {
  // ── Handle-каналы (request/response) ─────────────────────────────────
  GET_CRASH_RECOVERY: 'get-crash-recovery',
  SELECT_PROJECT_FOLDER: 'select-project-folder',
  SELECT_FILES: 'select-files',
  READ_ATTACHMENT: 'read-attachment',
  READ_FILE: 'read-file',
  WRITE_FILE: 'write-file',
  CHECK_OLLAMA: 'check-ollama',
  CHECK_QDRANT: 'check-qdrant',
  CHECK_MILVUS: 'check-milvus',
  LIST_OLLAMA_MODELS: 'list-ollama-models',
  LIST_PROVIDER_MODELS: 'list-provider-models',
  PING_PROVIDER: 'ping-provider',
  PULL_OLLAMA_MODEL: 'pull-ollama-model',
  DELETE_OLLAMA_MODEL: 'delete-ollama-model',
  CHECK_AGENT_PREREQUISITES: 'check-agent-prerequisites',
  RUN_TERMINAL_COMMAND: 'run-terminal-command',
  LIST_MEMORIES: 'list-memories',
  DELETE_MEMORY: 'delete-memory',
  LIST_SKILLS: 'list-skills',
  CREATE_SKILL: 'create-skill',
  DELETE_SKILL: 'delete-skill',
  SHARE_AS_GIST: 'share-as-gist',
  GET_CHAT_STORE: 'get-chat-store',
  CREATE_CHAT: 'create-chat',
  UPDATE_CHAT: 'update-chat',
  DELETE_CHAT: 'delete-chat',
  CREATE_CHAT_FOLDER: 'create-chat-folder',
  RENAME_CHAT_FOLDER: 'rename-chat-folder',
  UPDATE_CHAT_FOLDER: 'update-chat-folder',
  DELETE_CHAT_FOLDER: 'delete-chat-folder',
  SET_ACTIVE_CHAT: 'set-active-chat',
  MOVE_CHAT_TO_FOLDER: 'move-chat-to-folder',
  EXPORT_CHATS: 'export-chats',
  EXPORT_CHAT: 'export-chat',
  IMPORT_CHATS: 'import-chats',
  EXPORT_TRACE: 'export-trace',
  LOAD_CHAT_TRACE: 'load-chat-trace',
  CLEAR_CHAT_TRACE: 'clear-chat-trace',
  REPORT_TRACE_TO_GITHUB: 'report-trace-to-github',
  GET_AGENT_RUN_STATE: 'get-agent-run-state',
  STOP_AGENT: 'stop-agent',
  GET_RUN_CHECKPOINT: 'get-run-checkpoint',
  ROLLBACK_RUN: 'rollback-run',
  GET_PROJECT_TREE: 'get-project-tree',
  PREVIEW_AGENT_CONTEXT: 'preview-agent-context',
  SUMMARIZE_CONTEXT: 'summarize-context',
  LOAD_SETTINGS: 'load-settings',
  SAVE_SETTINGS: 'save-settings',
  RUN_AGENT: 'run-agent',
  LIST_PULL_REQUESTS: 'list-pull-requests',
  CREATE_ISSUE: 'create-issue',
  CREATE_PR: 'create-pr',
  LIST_ISSUES: 'list-issues',
  OPEN_ISSUE: 'open-issue',
  TRIGGER_GITHUB_WORKFLOW: 'trigger-github-workflow',
  READ_FILE_HISTORY: 'read-file-history',
  ADD_MCP_SERVER: 'add-mcp-server',
  REMOVE_MCP_SERVER: 'remove-mcp-server',
  CHECK_MCP_HEALTH: 'check-mcp-health',
  BENCHMARK_MODEL: 'benchmark-model',
  AUTO_INDEX_PROJECT: 'auto-index-project',
  FIND_IMPORT_CYCLES: 'find-import-cycles',
  CHECK_GITHUB_AUTH: 'check-github-auth',
  SELECT_GGUF_FILE: 'select-gguf-file',
  DOWNLOAD_GGUF: 'download-gguf',
  DELETE_GGUF_FILE: 'delete-gguf-file',
  VOTE_MEMORY: 'vote-memory',
  REGISTER_P2P_NODE: 'register-p2p-node',
  GET_P2P_CREDITS: 'get-p2p-credits',
  SHOW_AGENT_DONE_NOTIFICATION: 'show-agent-done-notification',
  GET_AGENT_METRICS: 'get-agent-metrics',
  LOAD_UI_LAYOUT: 'load-ui-layout',
  SAVE_UI_LAYOUT: 'save-ui-layout',

  // ── One-way (renderer → main) ─────────────────────────────────────────
  CANCEL_GGUF_DOWNLOAD: 'cancel-gguf-download',
  SAVE_APP_STATE: 'save-app-state',
  LOG_FRONTEND_ERROR: 'log-frontend-error',
  AGENT_CONFIRM_RESPONSE: 'agent-confirm-response',
  AGENT_CLARIFY_RESPONSE: 'agent-clarify-response',
  AGENT_PLAN_CONFIRM_RESPONSE: 'agent-plan-confirm-response',
  AGENT_PREVIEW_RESPONSE: 'agent-preview-response',
  AGENT_PREVIEW_HUNK_SELECTION: 'agent-preview-hunk-selection',
  OPEN_DEVTOOLS: 'open-devtools',
  RESTART_APP: 'restart-app',
  INSTALL_UPDATE: 'install-update',
  INSTALL_RUNTIME_UPDATE: 'install-runtime-update',
  OPEN_EXTERNAL: 'open-external',
  SHOW_ITEM_IN_FOLDER: 'show-item-in-folder',
  GET_COLLECTIVE_SYNC_STATUS: 'get-collective-sync-status',
  FLUSH_COLLECTIVE_MEMORY: 'flush-collective-memory',
  FORCE_SYNC_BUNDLED_RUNTIME: 'force-sync-bundled-runtime',
  CHECK_FOR_UPDATES: 'check-for-updates',

  // ── Broadcast (main → renderer) ───────────────────────────────────────
  AGENT_STREAM: 'agent-stream',
  OLLAMA_PULL_PROGRESS: 'ollama-pull-progress',
  GGUF_DOWNLOAD_PROGRESS: 'gguf-download-progress',
  AGENT_CONFIRM: 'agent-confirm',
  AGENT_CLARIFY: 'agent-clarify',
  SYSTEM_STATS: 'system-stats',
  PROGRESS_EVENT: 'progress-event',
  UPDATE_AVAILABLE: 'update-available',
  RUNTIME_UPDATE_READY: 'runtime-update-ready',
  DISMISS_RUNTIME_UPDATE: 'dismiss-runtime-update',
  MCP_HEALTH_STATUS: 'mcp-health-status'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
